# Generated by Django 5.2 on 2025-04-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_educationevent_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.JSONField(default=(0, 0)),
            preserve_default=False,
        ),
    ]
