# Generated by Django 5.2 on 2025-04-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_place_vicinity'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='types',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
